### ISSUE TITLE
About Operating System

### ISSUE THREAD

**Issue by alexandralau1900** [nikked/drl-crypto-portfolio-management#10]
Hi! May I ask what operating system you are running on? Thanks a bunch! I found that I couldn't download tensorflow 2.5.3  to mac.

**Comment by nikked** [comment]
Hey Alexandra and thank you for your interest in this project! 

I am using a mac too and TensorFlow 2.5.3 works fine for me. However, this project should work also with the latest version of TF (2.8.0) 😎

Anyway, I was able to install TF 2.5.3 with:

```
pip install tensorflow==2.5.3
```

**Comment by alexandralau1900** [comment]
problem solved :)
Your project really helped me a lot, thanks again!

**Comment by nikked** [comment]
Good to hear! Best of luck!
